adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp
app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basket

app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name='list'),
    path('add/<int:pk>/', basket.basket_add, name='add'),
    path('remove/<int:pk>/', basket.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from authapp import urls as authapp_urls
from mainapp import urls as mainapp_urls
from adminapp import urls as adminapp_urls
from basketapp import urls as basketapp_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include(adminapp_urls, namespace='admin_staff'), name='admin_staff'),

    path('auth/', include(authapp_urls, namespace='auth'), name='auth'),
    path('products/', include(mainapp_urls, namespace='products'), name='products'),
    path('basket/', include(basketapp_urls, namespace='basket'), name='basket'),

    path('', views.index, name='index'),
    path('contacts/', views.contacts, name='contacts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('product/<int:pk>/', product, name='product'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
]

geekshop/views.py
from django.shortcuts import render

from basketapp.models import Basket
from mainapp.models import Product


def index(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    title = 'geekshop'
    products = Product.objects.all()[:4]

    context = {
        'products': products,
        'some_name': 'hello',
        'title': title,
        'basket': basket,
    }
    return render(request, 'geekshop/index.html', context=context)


def contacts(request):
    return render(request, 'geekshop/contact.html')

geekshop/templates/geekshop/includes/inc_footer.html
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2017</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>

geekshop/templates/geekshop/includes/inc_main_menu.html
<div class="header clearfix">
    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="{% if request.resolver_match.route == '' %}
                    active
                  {% endif %}">домой</a></li>
        <li><a href="{% url 'products:category' 0 %}" class="{% if request.resolver_match.route == 'products/' %}
                        active
                      {% endif %}">продукты</a></li>
        <li><a href="{% url 'contacts' %}" class="{% if request.resolver_match.route == 'contacts/' %}
                        active
                      {% endif %}">контакты</a></li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:edit' %}">
                    {{ user.first_name|default:'Пользователь' }}
                </a>
            </li>
        {% endif %}
    {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin_staff:users' %}">
                    админка
            </a>
        </li>
    {% endif %}
            <li>
                {% if user.is_authenticated %}
                  <a href="{% url 'auth:logout' %}">выйти</a>
                {% else %}
                  <a href="{% url 'auth:login' %}">войти</a>
                {% endif %}
            </li>
    </ul>
    {% if basket %}
        <a href="{% url 'basket:list' %}" class="fa fa-shopping-basket">
            <span>
                {{ basket.0.total_cost|floatformat:0 }} руб
                ({{ basket.0.total_quantity }} шт.)
            </span>
        </a>
    {% endif %}
    <a href="#" class="search"></a>

</div>